version: '3.7'
services:
  bot_db_init:
    build: ./
    image: discord_bot_img
    container_name: discord_bot_ct
    # ports:
    #   - 8005:8000
    volumes:
      - ./:/usr/src/app
    restart: always
    ipc: host
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: python db_init/create_db.py
    # command: tail -F /dev/null